# Generated by Django 3.0.6 on 2020-05-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200523_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
